# Generated by Django 3.1.2 on 2020-11-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
