# Generated by Django 3.1.3 on 2020-12-08 12:15

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_auto_20201106_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='photo_main',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
