# Generated by Django 3.1.4 on 2020-12-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_auto_20201211_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
