# Generated by Django 3.1.4 on 2020-12-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_auto_20201211_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
