# Generated by Django 3.1.4 on 2020-12-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_auto_20201221_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='store_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
