# Generated by Django 3.1.4 on 2020-12-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_songs_store_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
