# Generated by Django 3.1.5 on 2021-01-12 10:17

from django.db import migrations
import sortedm2m.fields
import sortedm2m.operations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0010_auto_20201231_1657'),
    ]

    operations = [
        sortedm2m.operations.AlterSortedManyToManyField
        (
            model_name='playlist',
            name='beats',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='playlist_beats', to='beats.Songs'),
        ),
    ]
