# Generated by Django 3.2.15 on 2022-08-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0012_songs_exclusive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='exclusive',
            new_name='exclusive_content',
        ),
    ]
