# Generated by Django 3.1.6 on 2021-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210209_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='embedded_video_url',
            field=models.URLField(blank=True),
        ),
    ]
