# Generated by Django 3.1.1 on 2020-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201005_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
