# Generated by Django 3.1.1 on 2020-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cmera.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
