# Generated by Django 3.1.1 on 2020-10-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201015_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='users/avatar.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
