# Generated by Django 3.1.3 on 2020-12-08 10:08

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201208_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='avatar.jpg', upload_to='avatar'),
        ),
    ]
