# Generated by Django 3.1.3 on 2020-12-08 12:15

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='avatar.jpg', upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='users/%Y/%m/%d/'),
        ),
    ]
