# Generated by Django 3.1.5 on 2021-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210121_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blue_tick_verified',
            field=models.BooleanField(default=False),
        ),
    ]
