# Generated by Django 3.1.5 on 2021-01-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_blue_tick_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blue_tick_verified',
        ),
    ]
