# Generated by Django 3.1.6 on 2021-06-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210623_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
