# Generated by Django 3.1.6 on 2021-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210625_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='algorand_public_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
