# Generated by Django 3.1.5 on 2021-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('support_type', models.CharField(max_length=250)),
                ('support_message', models.TextField(max_length=500)),
                ('issue_resolved', models.CharField(choices=[(1, 'Issue unresolved'), (2, 'Pending'), (3, 'Issue Resolved')], default='Issue unresolved', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
