# Generated by Django 3.1.6 on 2021-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_auto_20210826_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='issue_resolved',
        ),
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'unresolved'), (2, 'Pending'), (3, 'resolved')], default=2),
        ),
    ]
