# Generated by Django 3.1.3 on 2020-11-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='verb_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
