# Generated by Django 3.1.5 on 2021-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'tweets'},
        ),
        migrations.AlterField(
            model_name='tweets',
            name='media_image',
            field=models.ImageField(blank=True, upload_to='tweets/%Y/%m/%d/'),
        ),
    ]
